version: '3.9'

services:
  db:
    image: postgres:15
    container_name: nest-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypost2
      POSTGRES_DB: nest
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nest']
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: nest-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      PGUSER: postgres
      PGPASSWORD: mypost2
      PGHOST: db
      PGDATABASE: nest
      PGPORT: 5432

volumes:
  db_data:
